"""empty message

Revision ID: 40bbaed131a1
Revises: 5c3b1c9c2c27
Create Date: 2023-08-18 08:33:04.888444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40bbaed131a1'
down_revision = '5c3b1c9c2c27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipo_prod',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carrito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.String(length=250), nullable=True),
    sa.Column('propiedades', sa.String(length=250), nullable=True),
    sa.Column('ingredientes_tec', sa.String(length=250), nullable=True),
    sa.Column('ingredientes_prin', sa.String(length=250), nullable=True),
    sa.Column('metodo_utilizacion', sa.String(length=250), nullable=True),
    sa.Column('tamanyo', sa.Integer(), nullable=True),
    sa.Column('medicion', sa.String(length=5), nullable=True),
    sa.Column('precio', sa.Integer(), nullable=True),
    sa.Column('id_tipo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_tipo'], ['tipo_prod.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carrito_prods',
    sa.Column('id_carrito', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_carrito'], ['carrito.id'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id_carrito', 'id_producto')
    )
    op.create_table('favorito',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_prod', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_prod'], ['producto.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id_user', 'id_prod')
    )
    op.create_table('pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_prod', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_prod'], ['producto.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'id_prod')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('apellido', sa.String(), nullable=True))
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('apellido')
        batch_op.drop_column('nombre')

    op.drop_table('pedido')
    op.drop_table('favorito')
    op.drop_table('carrito_prods')
    op.drop_table('producto')
    op.drop_table('carrito')
    op.drop_table('tipo_prod')
    # ### end Alembic commands ###
