"""empty message

Revision ID: 6def8f6fc4f2
Revises: 28b59a390295
Create Date: 2023-08-25 10:04:40.725797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6def8f6fc4f2'
down_revision = '28b59a390295'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('carrito_prods')
    with op.batch_alter_table('carrito', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_prod', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cantidad', sa.Integer(), nullable=True))
        batch_op.alter_column('id_user',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'producto', ['id_prod'], ['id'])
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carrito', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('id_user',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('cantidad')
        batch_op.drop_column('id_prod')

    op.create_table('carrito_prods',
    sa.Column('id_carrito', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_producto', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_carrito'], ['carrito.id'], name='carrito_prods_id_carrito_fkey'),
    sa.ForeignKeyConstraint(['id_producto'], ['producto.id'], name='carrito_prods_id_producto_fkey'),
    sa.PrimaryKeyConstraint('id_carrito', 'id_producto', name='carrito_prods_pkey')
    )
    # ### end Alembic commands ###
