"""empty message

Revision ID: 8e61cdc1be4d
Revises: f382d4beb889
Create Date: 2023-09-17 19:09:55.852343

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8e61cdc1be4d'
down_revision = 'f382d4beb889'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedido_local',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('id_prod', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_prod'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id', 'id_prod')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pedido_local')
    # ### end Alembic commands ###
