"""empty message

Revision ID: abe6e0aa7919
Revises: 8e61cdc1be4d
Create Date: 2023-10-16 07:41:15.297967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abe6e0aa7919'
down_revision = '8e61cdc1be4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dirección', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('ciudad', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('codigo_postal', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('codigo_postal')
        batch_op.drop_column('ciudad')
        batch_op.drop_column('dirección')

    # ### end Alembic commands ###
