"""empty message

Revision ID: f25c2e671e97
Revises: abe6e0aa7919
Create Date: 2023-10-16 08:46:53.708758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f25c2e671e97'
down_revision = 'abe6e0aa7919'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direccion', sa.String(), nullable=True))
        batch_op.drop_column('dirección')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dirección', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('direccion')

    # ### end Alembic commands ###
