"""empty message

Revision ID: f382d4beb889
Revises: 62ef56c868cf
Create Date: 2023-09-04 07:52:26.560998

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f382d4beb889'
down_revision = '62ef56c868cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###
